# Generated by Django 6.1.1 on 2026-10-03 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('capture', 'Capture'), ('teach', 'Teach')], default='capture', max_length=10)),
                ('title', models.CharField(default='Deploy an app on Thales Ops', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('screen', models.TextField(blank=True, default='')),
                ('phase', models.CharField(blank=True, default='', max_length=40)),
                ('activity', models.CharField(blank=True, default='idle', max_length=12)),
                ('coverage', models.JSONField(default=dict)),
                ('questions_asked', models.IntegerField(default=0)),
                ('last_question_at', models.FloatField(default=0)),
                ('debrief', models.JSONField(default=dict)),
                ('coached_phases', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.FloatField()),
                ('phase', models.CharField(blank=True, default='', max_length=40)),
                ('text', models.TextField()),
                ('judgment', models.FloatField(default=0)),
                ('asked', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='apprentice.session')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.FloatField()),
                ('action', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='apprentice.session')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.FloatField()),
                ('role', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='apprentice.session')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='produced_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_session', to='apprentice.workmap'),
        ),
        migrations.AddField(
            model_name='session',
            name='work_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teach_sessions', to='apprentice.workmap'),
        ),
    ]
