# Generated by Django 6.1.1 on 2026-10-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.FloatField()),
                ('image', models.BinaryField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyframes', to='apprentice.session')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='keyframe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='apprentice.keyframe'),
        ),
    ]
